//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Detail
    {
        [Required]
        public string Detail_ID { get; set; }
       
        public string Coures_ID { get; set; }

        public string Student_ID { get; set; }
   
        public virtual Coure Coure { get; set; }

        public virtual Student Student { get; set; }
    }
}
